namespace WindowsFormsApp1
{
	partial class Form1
	{
		/// <summary>
		/// 필수 디자이너 변수입니다.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary>
		/// 사용 중인 모든 리소스를 정리합니다.
		/// </summary>
		/// <param name="disposing">관리되는 리소스를 삭제해야 하면 true이고, 그렇지 않으면 false입니다.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing && (components != null))
			{
				components.Dispose();
			}
			base.Dispose(disposing);
		}

		#region Windows Form 디자이너에서 생성한 코드

		/// <summary>
		/// 디자이너 지원에 필요한 메서드입니다. 
		/// 이 메서드의 내용을 코드 편집기로 수정하지 마세요.
		/// </summary>
		private void InitializeComponent()
		{
			System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges();
			Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderEdges();
			Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
			this.bunifuTextBox2 = new Bunifu.UI.WinForms.BunifuTextBox();
			this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
			this.linkLabel2 = new System.Windows.Forms.LinkLabel();
			this.linkLabel1 = new System.Windows.Forms.LinkLabel();
			this.pictureBox1 = new System.Windows.Forms.PictureBox();
			this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.bunifuFormDock_form = new Bunifu.UI.WinForms.BunifuFormDock();
			this.tabPage1 = new System.Windows.Forms.TabPage();
			this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
			this.panel3 = new System.Windows.Forms.Panel();
			this.panel1 = new System.Windows.Forms.Panel();
			this.panel2 = new System.Windows.Forms.Panel();
			this.panel7 = new System.Windows.Forms.Panel();
			this.bunifuFormCaptionButton1 = new Bunifu.UI.WinForms.BunifuFormCaptionButton();
			this.bunifuFormCaptionButton2 = new Bunifu.UI.WinForms.BunifuFormCaptionButton();
			this.bunifuPages1 = new Bunifu.UI.WinForms.BunifuPages();
			this.tabPage2 = new System.Windows.Forms.TabPage();
			this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
			this.panel11 = new System.Windows.Forms.Panel();
			this.bunifuButton22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.panel12 = new System.Windows.Forms.Panel();
			this.bunifuButton23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
			this.panel10 = new System.Windows.Forms.Panel();
			this.bunifuTextBox7 = new Bunifu.UI.WinForms.BunifuTextBox();
			this.panel9 = new System.Windows.Forms.Panel();
			this.bunifuTextBox6 = new Bunifu.UI.WinForms.BunifuTextBox();
			this.panel8 = new System.Windows.Forms.Panel();
			this.bunifuTextBox5 = new Bunifu.UI.WinForms.BunifuTextBox();
			this.panel6 = new System.Windows.Forms.Panel();
			this.bunifuTextBox4 = new Bunifu.UI.WinForms.BunifuTextBox();
			this.panel5 = new System.Windows.Forms.Panel();
			this.bunifuTextBox3 = new Bunifu.UI.WinForms.BunifuTextBox();
			this.panel4 = new System.Windows.Forms.Panel();
			this.pictureBox2 = new System.Windows.Forms.PictureBox();
			this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
			this.bunifuFormDock_panel1 = new Bunifu.UI.WinForms.BunifuFormDock();
			((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
			this.tabPage1.SuspendLayout();
			this.bunifuPanel2.SuspendLayout();
			this.panel3.SuspendLayout();
			this.bunifuPages1.SuspendLayout();
			this.tabPage2.SuspendLayout();
			this.bunifuPanel3.SuspendLayout();
			this.panel11.SuspendLayout();
			((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
			this.bunifuPanel1.SuspendLayout();
			this.SuspendLayout();
			// 
			// bunifuTextBox2
			// 
			this.bunifuTextBox2.AcceptsReturn = false;
			this.bunifuTextBox2.AcceptsTab = false;
			this.bunifuTextBox2.AnimationSpeed = 200;
			this.bunifuTextBox2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox2.AutoSizeHeight = true;
			this.bunifuTextBox2.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox2.BackgroundImage")));
			this.bunifuTextBox2.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox2.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuTextBox2.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox2.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox2.BorderRadius = 10;
			this.bunifuTextBox2.BorderThickness = 1;
			this.bunifuTextBox2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.bunifuTextBox2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox2.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox2.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.bunifuTextBox2.DefaultText = "";
			this.bunifuTextBox2.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuTextBox2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuTextBox2.HideSelection = true;
			this.bunifuTextBox2.IconLeft = null;
			this.bunifuTextBox2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox2.IconPadding = 10;
			this.bunifuTextBox2.IconRight = null;
			this.bunifuTextBox2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox2.Lines = new string[0];
			this.bunifuTextBox2.Location = new System.Drawing.Point(60, 129);
			this.bunifuTextBox2.Margin = new System.Windows.Forms.Padding(6, 20, 6, 20);
			this.bunifuTextBox2.MaxLength = 32767;
			this.bunifuTextBox2.MinimumSize = new System.Drawing.Size(2, 2);
			this.bunifuTextBox2.Modified = false;
			this.bunifuTextBox2.Multiline = false;
			this.bunifuTextBox2.Name = "bunifuTextBox2";
			stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties1.FillColor = System.Drawing.Color.Empty;
			stateProperties1.ForeColor = System.Drawing.Color.Empty;
			stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox2.OnActiveState = stateProperties1;
			stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.bunifuTextBox2.OnDisabledState = stateProperties2;
			stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties3.FillColor = System.Drawing.Color.Empty;
			stateProperties3.ForeColor = System.Drawing.Color.Empty;
			stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox2.OnHoverState = stateProperties3;
			stateProperties4.BorderColor = System.Drawing.Color.Silver;
			stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			stateProperties4.ForeColor = System.Drawing.Color.Empty;
			stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox2.OnIdleState = stateProperties4;
			this.bunifuTextBox2.Padding = new System.Windows.Forms.Padding(6);
			this.bunifuTextBox2.PasswordChar = '*';
			this.bunifuTextBox2.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox2.PlaceholderText = "비밀번호를 입력해주세요.";
			this.bunifuTextBox2.ReadOnly = false;
			this.bunifuTextBox2.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox2.SelectedText = "";
			this.bunifuTextBox2.SelectionLength = 0;
			this.bunifuTextBox2.SelectionStart = 0;
			this.bunifuTextBox2.ShortcutsEnabled = true;
			this.bunifuTextBox2.Size = new System.Drawing.Size(411, 66);
			this.bunifuTextBox2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox2.TabIndex = 1;
			this.bunifuTextBox2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox2.TextMarginBottom = 0;
			this.bunifuTextBox2.TextMarginLeft = 3;
			this.bunifuTextBox2.TextMarginTop = 1;
			this.bunifuTextBox2.TextPlaceholder = "비밀번호를 입력해주세요.";
			this.bunifuTextBox2.UseSystemPasswordChar = false;
			this.bunifuTextBox2.WordWrap = true;
			// 
			// bunifuTextBox1
			// 
			this.bunifuTextBox1.AcceptsReturn = false;
			this.bunifuTextBox1.AcceptsTab = false;
			this.bunifuTextBox1.AnimationSpeed = 200;
			this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox1.AutoSizeHeight = true;
			this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
			this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox1.BorderRadius = 10;
			this.bunifuTextBox1.BorderThickness = 1;
			this.bunifuTextBox1.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.bunifuTextBox1.DefaultText = "";
			this.bunifuTextBox1.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuTextBox1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuTextBox1.HideSelection = true;
			this.bunifuTextBox1.IconLeft = null;
			this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox1.IconPadding = 10;
			this.bunifuTextBox1.IconRight = null;
			this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox1.Lines = new string[0];
			this.bunifuTextBox1.Location = new System.Drawing.Point(60, 30);
			this.bunifuTextBox1.Margin = new System.Windows.Forms.Padding(6, 20, 6, 0);
			this.bunifuTextBox1.MaxLength = 32767;
			this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(2, 2);
			this.bunifuTextBox1.Modified = false;
			this.bunifuTextBox1.Multiline = false;
			this.bunifuTextBox1.Name = "bunifuTextBox1";
			stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties5.FillColor = System.Drawing.Color.Empty;
			stateProperties5.ForeColor = System.Drawing.Color.Empty;
			stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox1.OnActiveState = stateProperties5;
			stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.bunifuTextBox1.OnDisabledState = stateProperties6;
			stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties7.FillColor = System.Drawing.Color.Empty;
			stateProperties7.ForeColor = System.Drawing.Color.Empty;
			stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox1.OnHoverState = stateProperties7;
			stateProperties8.BorderColor = System.Drawing.Color.Silver;
			stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			stateProperties8.ForeColor = System.Drawing.Color.Empty;
			stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox1.OnIdleState = stateProperties8;
			this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(6);
			this.bunifuTextBox1.PasswordChar = '\0';
			this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox1.PlaceholderText = "ID를 입력해주세요.";
			this.bunifuTextBox1.ReadOnly = false;
			this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox1.SelectedText = "";
			this.bunifuTextBox1.SelectionLength = 0;
			this.bunifuTextBox1.SelectionStart = 0;
			this.bunifuTextBox1.ShortcutsEnabled = true;
			this.bunifuTextBox1.Size = new System.Drawing.Size(411, 69);
			this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox1.TabIndex = 0;
			this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox1.TextMarginBottom = 0;
			this.bunifuTextBox1.TextMarginLeft = 3;
			this.bunifuTextBox1.TextMarginTop = 1;
			this.bunifuTextBox1.TextPlaceholder = "ID를 입력해주세요.";
			this.bunifuTextBox1.UseSystemPasswordChar = false;
			this.bunifuTextBox1.WordWrap = true;
			// 
			// linkLabel2
			// 
			this.linkLabel2.AutoSize = true;
			this.linkLabel2.BackColor = System.Drawing.Color.Transparent;
			this.linkLabel2.Dock = System.Windows.Forms.DockStyle.Left;
			this.linkLabel2.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			this.linkLabel2.Location = new System.Drawing.Point(0, 0);
			this.linkLabel2.Margin = new System.Windows.Forms.Padding(6, 0, 6, 0);
			this.linkLabel2.Name = "linkLabel2";
			this.linkLabel2.Size = new System.Drawing.Size(89, 29);
			this.linkLabel2.TabIndex = 7;
			this.linkLabel2.TabStop = true;
			this.linkLabel2.Text = "계정찾기";
			this.linkLabel2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
			// 
			// linkLabel1
			// 
			this.linkLabel1.AutoSize = true;
			this.linkLabel1.BackColor = System.Drawing.Color.Transparent;
			this.linkLabel1.Dock = System.Windows.Forms.DockStyle.Right;
			this.linkLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.999999F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			this.linkLabel1.Location = new System.Drawing.Point(322, 0);
			this.linkLabel1.Margin = new System.Windows.Forms.Padding(6, 0, 6, 0);
			this.linkLabel1.Name = "linkLabel1";
			this.linkLabel1.Size = new System.Drawing.Size(89, 29);
			this.linkLabel1.TabIndex = 6;
			this.linkLabel1.TabStop = true;
			this.linkLabel1.Text = "회원가입";
			this.linkLabel1.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.linkLabel1.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.linkLabel1_LinkClicked);
			// 
			// pictureBox1
			// 
			this.pictureBox1.BackColor = System.Drawing.Color.Transparent;
			this.pictureBox1.Dock = System.Windows.Forms.DockStyle.Top;
			this.pictureBox1.Image = global::WindowsFormsApp1.Properties.Resources.BCU_Logo;
			this.pictureBox1.Location = new System.Drawing.Point(0, 0);
			this.pictureBox1.Margin = new System.Windows.Forms.Padding(6);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new System.Drawing.Size(531, 220);
			this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.pictureBox1.TabIndex = 5;
			this.pictureBox1.TabStop = false;
			// 
			// bunifuButton21
			// 
			this.bunifuButton21.AllowAnimations = true;
			this.bunifuButton21.AllowMouseEffects = true;
			this.bunifuButton21.AllowToggling = false;
			this.bunifuButton21.AnimationSpeed = 200;
			this.bunifuButton21.AutoGenerateColors = false;
			this.bunifuButton21.AutoRoundBorders = false;
			this.bunifuButton21.AutoSizeLeftIcon = true;
			this.bunifuButton21.AutoSizeRightIcon = true;
			this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton21.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
			this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton21.ButtonText = "로그인";
			this.bunifuButton21.ButtonTextMarginLeft = 0;
			this.bunifuButton21.ColorContrastOnClick = 45;
			this.bunifuButton21.ColorContrastOnHover = 45;
			this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges1.BottomLeft = true;
			borderEdges1.BottomRight = true;
			borderEdges1.TopLeft = true;
			borderEdges1.TopRight = true;
			this.bunifuButton21.CustomizableEdges = borderEdges1;
			this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton21.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			this.bunifuButton21.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(129)));
			this.bunifuButton21.ForeColor = System.Drawing.Color.White;
			this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton21.IconMarginLeft = 11;
			this.bunifuButton21.IconPadding = 10;
			this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton21.IconSize = 25;
			this.bunifuButton21.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton21.IdleBorderRadius = 10;
			this.bunifuButton21.IdleBorderThickness = 1;
			this.bunifuButton21.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton21.IdleIconLeftImage = null;
			this.bunifuButton21.IdleIconRightImage = null;
			this.bunifuButton21.IndicateFocus = false;
			this.bunifuButton21.Location = new System.Drawing.Point(60, 225);
			this.bunifuButton21.Margin = new System.Windows.Forms.Padding(6);
			this.bunifuButton21.Name = "bunifuButton21";
			this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton21.OnDisabledState.BorderRadius = 10;
			this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton21.OnDisabledState.BorderThickness = 1;
			this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton21.OnDisabledState.IconLeftImage = null;
			this.bunifuButton21.OnDisabledState.IconRightImage = null;
			this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton21.onHoverState.BorderRadius = 10;
			this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton21.onHoverState.BorderThickness = 1;
			this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton21.onHoverState.IconLeftImage = null;
			this.bunifuButton21.onHoverState.IconRightImage = null;
			this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton21.OnIdleState.BorderRadius = 10;
			this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton21.OnIdleState.BorderThickness = 1;
			this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton21.OnIdleState.IconLeftImage = null;
			this.bunifuButton21.OnIdleState.IconRightImage = null;
			this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton21.OnPressedState.BorderRadius = 10;
			this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton21.OnPressedState.BorderThickness = 1;
			this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton21.OnPressedState.IconLeftImage = null;
			this.bunifuButton21.OnPressedState.IconRightImage = null;
			this.bunifuButton21.Size = new System.Drawing.Size(411, 78);
			this.bunifuButton21.TabIndex = 2;
			this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton21.TextMarginLeft = 0;
			this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton21.UseDefaultRadiusAndThickness = true;
			this.bunifuButton21.Click += new System.EventHandler(this.bunifuButton21_Click);
			// 
			// bunifuFormDock_form
			// 
			this.bunifuFormDock_form.AllowFormDragging = true;
			this.bunifuFormDock_form.AllowFormDropShadow = true;
			this.bunifuFormDock_form.AllowFormResizing = false;
			this.bunifuFormDock_form.AllowHidingBottomRegion = true;
			this.bunifuFormDock_form.AllowOpacityChangesWhileDragging = false;
			this.bunifuFormDock_form.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_form.BorderOptions.BottomBorder.BorderThickness = 1;
			this.bunifuFormDock_form.BorderOptions.BottomBorder.ShowBorder = true;
			this.bunifuFormDock_form.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_form.BorderOptions.LeftBorder.BorderThickness = 1;
			this.bunifuFormDock_form.BorderOptions.LeftBorder.ShowBorder = true;
			this.bunifuFormDock_form.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_form.BorderOptions.RightBorder.BorderThickness = 1;
			this.bunifuFormDock_form.BorderOptions.RightBorder.ShowBorder = true;
			this.bunifuFormDock_form.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_form.BorderOptions.TopBorder.BorderThickness = 1;
			this.bunifuFormDock_form.BorderOptions.TopBorder.ShowBorder = true;
			this.bunifuFormDock_form.ContainerControl = this;
			this.bunifuFormDock_form.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
			this.bunifuFormDock_form.DockingIndicatorsOpacity = 0.5D;
			this.bunifuFormDock_form.DockingOptions.DockAll = true;
			this.bunifuFormDock_form.DockingOptions.DockBottomLeft = true;
			this.bunifuFormDock_form.DockingOptions.DockBottomRight = true;
			this.bunifuFormDock_form.DockingOptions.DockFullScreen = true;
			this.bunifuFormDock_form.DockingOptions.DockLeft = true;
			this.bunifuFormDock_form.DockingOptions.DockRight = true;
			this.bunifuFormDock_form.DockingOptions.DockTopLeft = true;
			this.bunifuFormDock_form.DockingOptions.DockTopRight = true;
			this.bunifuFormDock_form.FormDraggingOpacity = 0.9D;
			this.bunifuFormDock_form.ParentForm = this;
			this.bunifuFormDock_form.ShowCursorChanges = true;
			this.bunifuFormDock_form.ShowDockingIndicators = false;
			this.bunifuFormDock_form.TitleBarOptions.AllowFormDragging = true;
			this.bunifuFormDock_form.TitleBarOptions.BunifuFormDock = this.bunifuFormDock_form;
			this.bunifuFormDock_form.TitleBarOptions.DoubleClickToExpandWindow = true;
			this.bunifuFormDock_form.TitleBarOptions.TitleBarControl = this;
			this.bunifuFormDock_form.TitleBarOptions.UseBackColorOnDockingIndicators = false;
			// 
			// tabPage1
			// 
			this.tabPage1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
			this.tabPage1.Controls.Add(this.bunifuPanel2);
			this.tabPage1.Controls.Add(this.pictureBox1);
			this.tabPage1.Location = new System.Drawing.Point(8, 8);
			this.tabPage1.Margin = new System.Windows.Forms.Padding(0);
			this.tabPage1.Name = "tabPage1";
			this.tabPage1.Size = new System.Drawing.Size(531, 901);
			this.tabPage1.TabIndex = 0;
			this.tabPage1.Text = "로그인";
			// 
			// bunifuPanel2
			// 
			this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
			this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
			this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
			this.bunifuPanel2.BorderRadius = 3;
			this.bunifuPanel2.BorderThickness = 1;
			this.bunifuPanel2.Controls.Add(this.panel3);
			this.bunifuPanel2.Controls.Add(this.bunifuButton21);
			this.bunifuPanel2.Controls.Add(this.panel1);
			this.bunifuPanel2.Controls.Add(this.bunifuTextBox2);
			this.bunifuPanel2.Controls.Add(this.panel2);
			this.bunifuPanel2.Controls.Add(this.bunifuTextBox1);
			this.bunifuPanel2.Controls.Add(this.panel7);
			this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
			this.bunifuPanel2.Location = new System.Drawing.Point(0, 220);
			this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(10);
			this.bunifuPanel2.Name = "bunifuPanel2";
			this.bunifuPanel2.Padding = new System.Windows.Forms.Padding(60, 0, 60, 0);
			this.bunifuPanel2.ShowBorders = true;
			this.bunifuPanel2.Size = new System.Drawing.Size(531, 681);
			this.bunifuPanel2.TabIndex = 10;
			// 
			// panel3
			// 
			this.panel3.Controls.Add(this.linkLabel2);
			this.panel3.Controls.Add(this.linkLabel1);
			this.panel3.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel3.Location = new System.Drawing.Point(60, 303);
			this.panel3.Name = "panel3";
			this.panel3.Size = new System.Drawing.Size(411, 57);
			this.panel3.TabIndex = 12;
			// 
			// panel1
			// 
			this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel1.Location = new System.Drawing.Point(60, 195);
			this.panel1.Name = "panel1";
			this.panel1.Size = new System.Drawing.Size(411, 30);
			this.panel1.TabIndex = 10;
			// 
			// panel2
			// 
			this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel2.Location = new System.Drawing.Point(60, 99);
			this.panel2.Name = "panel2";
			this.panel2.Size = new System.Drawing.Size(411, 30);
			this.panel2.TabIndex = 1;
			// 
			// panel7
			// 
			this.panel7.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel7.Location = new System.Drawing.Point(60, 0);
			this.panel7.Name = "panel7";
			this.panel7.Size = new System.Drawing.Size(411, 30);
			this.panel7.TabIndex = 13;
			// 
			// bunifuFormCaptionButton1
			// 
			this.bunifuFormCaptionButton1.AllowAnimations = true;
			this.bunifuFormCaptionButton1.AllowBorderColorChanges = true;
			this.bunifuFormCaptionButton1.AllowDefaults = true;
			this.bunifuFormCaptionButton1.AllowMouseEffects = true;
			this.bunifuFormCaptionButton1.AnimationSpeed = 200;
			this.bunifuFormCaptionButton1.AutoSizeCaptions = true;
			this.bunifuFormCaptionButton1.BackColor = System.Drawing.Color.Transparent;
			this.bunifuFormCaptionButton1.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuFormCaptionButton1.BackHoverColor = System.Drawing.Color.LightGray;
			this.bunifuFormCaptionButton1.BackPressedColor = System.Drawing.Color.Silver;
			this.bunifuFormCaptionButton1.BorderColor = System.Drawing.Color.Transparent;
			this.bunifuFormCaptionButton1.BorderHoverColor = System.Drawing.Color.DarkGray;
			this.bunifuFormCaptionButton1.BorderPressedColor = System.Drawing.Color.DarkGray;
			this.bunifuFormCaptionButton1.BorderRadius = 1;
			this.bunifuFormCaptionButton1.BorderStyle = Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderStyles.Solid;
			this.bunifuFormCaptionButton1.BorderThickness = 1;
			this.bunifuFormCaptionButton1.CaptionType = Bunifu.UI.WinForms.BunifuFormCaptionButton.CaptionTypes.Close;
			this.bunifuFormCaptionButton1.ColorContrastOnClick = 30;
			this.bunifuFormCaptionButton1.ColorContrastOnHover = 30;
			this.bunifuFormCaptionButton1.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges3.BottomLeft = true;
			borderEdges3.BottomRight = true;
			borderEdges3.TopLeft = true;
			borderEdges3.TopRight = true;
			this.bunifuFormCaptionButton1.CustomizableEdges = borderEdges3;
			this.bunifuFormCaptionButton1.DefaultBorderColor = System.Drawing.Color.Transparent;
			this.bunifuFormCaptionButton1.DefaultColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuFormCaptionButton1.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuFormCaptionButton1.Dock = System.Windows.Forms.DockStyle.Right;
			this.bunifuFormCaptionButton1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(128)))));
			this.bunifuFormCaptionButton1.IconColor = System.Drawing.Color.OrangeRed;
			this.bunifuFormCaptionButton1.IconHoverColor = System.Drawing.Color.Red;
			this.bunifuFormCaptionButton1.IconPressedColor = System.Drawing.Color.Black;
			this.bunifuFormCaptionButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuFormCaptionButton1.Image")));
			this.bunifuFormCaptionButton1.ImageMargin = new System.Windows.Forms.Padding(1, 1, 0, 0);
			this.bunifuFormCaptionButton1.ImageSize = new System.Drawing.Size(20, 20);
			this.bunifuFormCaptionButton1.Location = new System.Drawing.Point(813, 0);
			this.bunifuFormCaptionButton1.Margin = new System.Windows.Forms.Padding(6);
			this.bunifuFormCaptionButton1.Name = "bunifuFormCaptionButton1";
			this.bunifuFormCaptionButton1.ShowBorders = true;
			this.bunifuFormCaptionButton1.Size = new System.Drawing.Size(74, 62);
			this.bunifuFormCaptionButton1.TabIndex = 0;
			this.bunifuFormCaptionButton1.Click += new System.EventHandler(this.bunifuFormCaptionButton1_Click);
			// 
			// bunifuFormCaptionButton2
			// 
			this.bunifuFormCaptionButton2.AllowAnimations = true;
			this.bunifuFormCaptionButton2.AllowBorderColorChanges = true;
			this.bunifuFormCaptionButton2.AllowDefaults = true;
			this.bunifuFormCaptionButton2.AllowMouseEffects = true;
			this.bunifuFormCaptionButton2.AnimationSpeed = 200;
			this.bunifuFormCaptionButton2.AutoSizeCaptions = true;
			this.bunifuFormCaptionButton2.BackColor = System.Drawing.Color.Transparent;
			this.bunifuFormCaptionButton2.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuFormCaptionButton2.BackHoverColor = System.Drawing.Color.LightGray;
			this.bunifuFormCaptionButton2.BackPressedColor = System.Drawing.Color.Silver;
			this.bunifuFormCaptionButton2.BorderColor = System.Drawing.Color.Transparent;
			this.bunifuFormCaptionButton2.BorderHoverColor = System.Drawing.Color.DarkGray;
			this.bunifuFormCaptionButton2.BorderPressedColor = System.Drawing.Color.DarkGray;
			this.bunifuFormCaptionButton2.BorderRadius = 1;
			this.bunifuFormCaptionButton2.BorderStyle = Bunifu.UI.WinForms.BunifuFormCaptionButton.BorderStyles.Solid;
			this.bunifuFormCaptionButton2.BorderThickness = 1;
			this.bunifuFormCaptionButton2.CaptionType = Bunifu.UI.WinForms.BunifuFormCaptionButton.CaptionTypes.Minimize;
			this.bunifuFormCaptionButton2.ColorContrastOnClick = 30;
			this.bunifuFormCaptionButton2.ColorContrastOnHover = 30;
			this.bunifuFormCaptionButton2.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges2.BottomLeft = true;
			borderEdges2.BottomRight = true;
			borderEdges2.TopLeft = true;
			borderEdges2.TopRight = true;
			this.bunifuFormCaptionButton2.CustomizableEdges = borderEdges2;
			this.bunifuFormCaptionButton2.DefaultBorderColor = System.Drawing.Color.Transparent;
			this.bunifuFormCaptionButton2.DefaultColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuFormCaptionButton2.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuFormCaptionButton2.Dock = System.Windows.Forms.DockStyle.Right;
			this.bunifuFormCaptionButton2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
			this.bunifuFormCaptionButton2.IconColor = System.Drawing.Color.Black;
			this.bunifuFormCaptionButton2.IconHoverColor = System.Drawing.Color.Black;
			this.bunifuFormCaptionButton2.IconPressedColor = System.Drawing.Color.Black;
			this.bunifuFormCaptionButton2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuFormCaptionButton2.Image")));
			this.bunifuFormCaptionButton2.ImageMargin = new System.Windows.Forms.Padding(1, 1, 0, 0);
			this.bunifuFormCaptionButton2.ImageSize = new System.Drawing.Size(18, 18);
			this.bunifuFormCaptionButton2.Location = new System.Drawing.Point(739, 0);
			this.bunifuFormCaptionButton2.Margin = new System.Windows.Forms.Padding(6);
			this.bunifuFormCaptionButton2.Name = "bunifuFormCaptionButton2";
			this.bunifuFormCaptionButton2.ShowBorders = true;
			this.bunifuFormCaptionButton2.Size = new System.Drawing.Size(74, 62);
			this.bunifuFormCaptionButton2.TabIndex = 0;
			this.bunifuFormCaptionButton2.Click += new System.EventHandler(this.bunifuFormCaptionButton2_Click);
			// 
			// bunifuPages1
			// 
			this.bunifuPages1.Alignment = System.Windows.Forms.TabAlignment.Bottom;
			this.bunifuPages1.AllowTransitions = true;
			this.bunifuPages1.Controls.Add(this.tabPage1);
			this.bunifuPages1.Controls.Add(this.tabPage2);
			this.bunifuPages1.Dock = System.Windows.Forms.DockStyle.Left;
			this.bunifuPages1.Location = new System.Drawing.Point(0, 0);
			this.bunifuPages1.Margin = new System.Windows.Forms.Padding(0);
			this.bunifuPages1.Multiline = true;
			this.bunifuPages1.Name = "bunifuPages1";
			this.bunifuPages1.Page = this.tabPage1;
			this.bunifuPages1.PageIndex = 0;
			this.bunifuPages1.PageName = "tabPage1";
			this.bunifuPages1.PageTitle = "로그인";
			this.bunifuPages1.SelectedIndex = 0;
			this.bunifuPages1.Size = new System.Drawing.Size(547, 948);
			this.bunifuPages1.TabIndex = 2;
			animation1.AnimateOnlyDifferences = true;
			animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
			animation1.LeafCoeff = 0F;
			animation1.MaxTime = 1F;
			animation1.MinTime = 0F;
			animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
			animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
			animation1.MosaicSize = 0;
			animation1.Padding = new System.Windows.Forms.Padding(0, 0, 0, 0);
			animation1.RotateCoeff = 0F;
			animation1.RotateLimit = 0F;
			animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
			animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
			animation1.TimeCoeff = 0F;
			animation1.TransparencyCoeff = 1F;
			this.bunifuPages1.Transition = animation1;
			this.bunifuPages1.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Transparent;
			// 
			// tabPage2
			// 
			this.tabPage2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
			this.tabPage2.Controls.Add(this.bunifuPanel3);
			this.tabPage2.Controls.Add(this.pictureBox2);
			this.tabPage2.Location = new System.Drawing.Point(8, 8);
			this.tabPage2.Margin = new System.Windows.Forms.Padding(0);
			this.tabPage2.Name = "tabPage2";
			this.tabPage2.Size = new System.Drawing.Size(531, 901);
			this.tabPage2.TabIndex = 1;
			this.tabPage2.Text = "회원가입";
			// 
			// bunifuPanel3
			// 
			this.bunifuPanel3.BackgroundColor = System.Drawing.Color.Transparent;
			this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
			this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
			this.bunifuPanel3.BorderRadius = 3;
			this.bunifuPanel3.BorderThickness = 1;
			this.bunifuPanel3.Controls.Add(this.panel11);
			this.bunifuPanel3.Controls.Add(this.panel10);
			this.bunifuPanel3.Controls.Add(this.bunifuTextBox7);
			this.bunifuPanel3.Controls.Add(this.panel9);
			this.bunifuPanel3.Controls.Add(this.bunifuTextBox6);
			this.bunifuPanel3.Controls.Add(this.panel8);
			this.bunifuPanel3.Controls.Add(this.bunifuTextBox5);
			this.bunifuPanel3.Controls.Add(this.panel6);
			this.bunifuPanel3.Controls.Add(this.bunifuTextBox4);
			this.bunifuPanel3.Controls.Add(this.panel5);
			this.bunifuPanel3.Controls.Add(this.bunifuTextBox3);
			this.bunifuPanel3.Controls.Add(this.panel4);
			this.bunifuPanel3.Dock = System.Windows.Forms.DockStyle.Fill;
			this.bunifuPanel3.Location = new System.Drawing.Point(0, 220);
			this.bunifuPanel3.Margin = new System.Windows.Forms.Padding(10);
			this.bunifuPanel3.Name = "bunifuPanel3";
			this.bunifuPanel3.Padding = new System.Windows.Forms.Padding(60, 0, 60, 0);
			this.bunifuPanel3.ShowBorders = true;
			this.bunifuPanel3.Size = new System.Drawing.Size(531, 681);
			this.bunifuPanel3.TabIndex = 11;
			// 
			// panel11
			// 
			this.panel11.Controls.Add(this.bunifuButton22);
			this.panel11.Controls.Add(this.panel12);
			this.panel11.Controls.Add(this.bunifuButton23);
			this.panel11.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel11.Location = new System.Drawing.Point(60, 519);
			this.panel11.Name = "panel11";
			this.panel11.Size = new System.Drawing.Size(411, 107);
			this.panel11.TabIndex = 22;
			// 
			// bunifuButton22
			// 
			this.bunifuButton22.AllowAnimations = true;
			this.bunifuButton22.AllowMouseEffects = true;
			this.bunifuButton22.AllowToggling = false;
			this.bunifuButton22.AnimationSpeed = 200;
			this.bunifuButton22.AutoGenerateColors = false;
			this.bunifuButton22.AutoRoundBorders = false;
			this.bunifuButton22.AutoSizeLeftIcon = true;
			this.bunifuButton22.AutoSizeRightIcon = true;
			this.bunifuButton22.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton22.BackColor1 = System.Drawing.Color.DodgerBlue;
			this.bunifuButton22.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton22.BackgroundImage")));
			this.bunifuButton22.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton22.ButtonText = "가입하기";
			this.bunifuButton22.ButtonTextMarginLeft = 0;
			this.bunifuButton22.ColorContrastOnClick = 45;
			this.bunifuButton22.ColorContrastOnHover = 45;
			this.bunifuButton22.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges4.BottomLeft = true;
			borderEdges4.BottomRight = true;
			borderEdges4.TopLeft = true;
			borderEdges4.TopRight = true;
			this.bunifuButton22.CustomizableEdges = borderEdges4;
			this.bunifuButton22.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton22.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton22.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton22.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton22.Dock = System.Windows.Forms.DockStyle.Fill;
			this.bunifuButton22.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			this.bunifuButton22.Font = new System.Drawing.Font("Microsoft Sans Serif", 16.125F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton22.ForeColor = System.Drawing.Color.White;
			this.bunifuButton22.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton22.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton22.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton22.IconMarginLeft = 11;
			this.bunifuButton22.IconPadding = 10;
			this.bunifuButton22.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton22.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton22.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton22.IconSize = 25;
			this.bunifuButton22.IdleBorderColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton22.IdleBorderRadius = 10;
			this.bunifuButton22.IdleBorderThickness = 1;
			this.bunifuButton22.IdleFillColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton22.IdleIconLeftImage = null;
			this.bunifuButton22.IdleIconRightImage = null;
			this.bunifuButton22.IndicateFocus = false;
			this.bunifuButton22.Location = new System.Drawing.Point(130, 0);
			this.bunifuButton22.Margin = new System.Windows.Forms.Padding(6);
			this.bunifuButton22.Name = "bunifuButton22";
			this.bunifuButton22.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton22.OnDisabledState.BorderRadius = 10;
			this.bunifuButton22.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton22.OnDisabledState.BorderThickness = 1;
			this.bunifuButton22.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton22.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton22.OnDisabledState.IconLeftImage = null;
			this.bunifuButton22.OnDisabledState.IconRightImage = null;
			this.bunifuButton22.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton22.onHoverState.BorderRadius = 10;
			this.bunifuButton22.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton22.onHoverState.BorderThickness = 1;
			this.bunifuButton22.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton22.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton22.onHoverState.IconLeftImage = null;
			this.bunifuButton22.onHoverState.IconRightImage = null;
			this.bunifuButton22.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton22.OnIdleState.BorderRadius = 10;
			this.bunifuButton22.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton22.OnIdleState.BorderThickness = 1;
			this.bunifuButton22.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
			this.bunifuButton22.OnIdleState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton22.OnIdleState.IconLeftImage = null;
			this.bunifuButton22.OnIdleState.IconRightImage = null;
			this.bunifuButton22.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton22.OnPressedState.BorderRadius = 10;
			this.bunifuButton22.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton22.OnPressedState.BorderThickness = 1;
			this.bunifuButton22.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton22.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton22.OnPressedState.IconLeftImage = null;
			this.bunifuButton22.OnPressedState.IconRightImage = null;
			this.bunifuButton22.Size = new System.Drawing.Size(281, 107);
			this.bunifuButton22.TabIndex = 3;
			this.bunifuButton22.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton22.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton22.TextMarginLeft = 0;
			this.bunifuButton22.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton22.UseDefaultRadiusAndThickness = true;
			this.bunifuButton22.Click += new System.EventHandler(this.bunifuButton22_Click_1);
			// 
			// panel12
			// 
			this.panel12.Dock = System.Windows.Forms.DockStyle.Left;
			this.panel12.Location = new System.Drawing.Point(104, 0);
			this.panel12.Name = "panel12";
			this.panel12.Size = new System.Drawing.Size(26, 107);
			this.panel12.TabIndex = 22;
			// 
			// bunifuButton23
			// 
			this.bunifuButton23.AllowAnimations = true;
			this.bunifuButton23.AllowMouseEffects = true;
			this.bunifuButton23.AllowToggling = false;
			this.bunifuButton23.AnimationSpeed = 200;
			this.bunifuButton23.AutoGenerateColors = false;
			this.bunifuButton23.AutoRoundBorders = false;
			this.bunifuButton23.AutoSizeLeftIcon = true;
			this.bunifuButton23.AutoSizeRightIcon = true;
			this.bunifuButton23.BackColor = System.Drawing.Color.Transparent;
			this.bunifuButton23.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuButton23.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton23.BackgroundImage")));
			this.bunifuButton23.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton23.ButtonText = "🔙";
			this.bunifuButton23.ButtonTextMarginLeft = 0;
			this.bunifuButton23.ColorContrastOnClick = 45;
			this.bunifuButton23.ColorContrastOnHover = 45;
			this.bunifuButton23.Cursor = System.Windows.Forms.Cursors.Hand;
			borderEdges5.BottomLeft = true;
			borderEdges5.BottomRight = true;
			borderEdges5.TopLeft = true;
			borderEdges5.TopRight = true;
			this.bunifuButton23.CustomizableEdges = borderEdges5;
			this.bunifuButton23.DialogResult = System.Windows.Forms.DialogResult.None;
			this.bunifuButton23.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton23.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton23.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton23.Dock = System.Windows.Forms.DockStyle.Left;
			this.bunifuButton23.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
			this.bunifuButton23.Font = new System.Drawing.Font("Microsoft Sans Serif", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
			this.bunifuButton23.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
			this.bunifuButton23.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
			this.bunifuButton23.IconLeftCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton23.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
			this.bunifuButton23.IconMarginLeft = 11;
			this.bunifuButton23.IconPadding = 10;
			this.bunifuButton23.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
			this.bunifuButton23.IconRightCursor = System.Windows.Forms.Cursors.Default;
			this.bunifuButton23.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
			this.bunifuButton23.IconSize = 25;
			this.bunifuButton23.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuButton23.IdleBorderRadius = 10;
			this.bunifuButton23.IdleBorderThickness = 1;
			this.bunifuButton23.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuButton23.IdleIconLeftImage = null;
			this.bunifuButton23.IdleIconRightImage = null;
			this.bunifuButton23.IndicateFocus = false;
			this.bunifuButton23.Location = new System.Drawing.Point(0, 0);
			this.bunifuButton23.Margin = new System.Windows.Forms.Padding(6);
			this.bunifuButton23.Name = "bunifuButton23";
			this.bunifuButton23.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
			this.bunifuButton23.OnDisabledState.BorderRadius = 10;
			this.bunifuButton23.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton23.OnDisabledState.BorderThickness = 1;
			this.bunifuButton23.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuButton23.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
			this.bunifuButton23.OnDisabledState.IconLeftImage = null;
			this.bunifuButton23.OnDisabledState.IconRightImage = null;
			this.bunifuButton23.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton23.onHoverState.BorderRadius = 10;
			this.bunifuButton23.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton23.onHoverState.BorderThickness = 1;
			this.bunifuButton23.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuButton23.onHoverState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton23.onHoverState.IconLeftImage = null;
			this.bunifuButton23.onHoverState.IconRightImage = null;
			this.bunifuButton23.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuButton23.OnIdleState.BorderRadius = 10;
			this.bunifuButton23.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton23.OnIdleState.BorderThickness = 1;
			this.bunifuButton23.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuButton23.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(100)))), ((int)(((byte)(100)))), ((int)(((byte)(100)))));
			this.bunifuButton23.OnIdleState.IconLeftImage = null;
			this.bunifuButton23.OnIdleState.IconRightImage = null;
			this.bunifuButton23.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton23.OnPressedState.BorderRadius = 10;
			this.bunifuButton23.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
			this.bunifuButton23.OnPressedState.BorderThickness = 1;
			this.bunifuButton23.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
			this.bunifuButton23.OnPressedState.ForeColor = System.Drawing.Color.White;
			this.bunifuButton23.OnPressedState.IconLeftImage = null;
			this.bunifuButton23.OnPressedState.IconRightImage = null;
			this.bunifuButton23.Size = new System.Drawing.Size(104, 107);
			this.bunifuButton23.TabIndex = 4;
			this.bunifuButton23.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
			this.bunifuButton23.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
			this.bunifuButton23.TextMarginLeft = 0;
			this.bunifuButton23.TextPadding = new System.Windows.Forms.Padding(0);
			this.bunifuButton23.UseDefaultRadiusAndThickness = true;
			// 
			// panel10
			// 
			this.panel10.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel10.Location = new System.Drawing.Point(60, 489);
			this.panel10.Name = "panel10";
			this.panel10.Size = new System.Drawing.Size(411, 30);
			this.panel10.TabIndex = 21;
			// 
			// bunifuTextBox7
			// 
			this.bunifuTextBox7.AcceptsReturn = false;
			this.bunifuTextBox7.AcceptsTab = false;
			this.bunifuTextBox7.AnimationSpeed = 200;
			this.bunifuTextBox7.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox7.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox7.AutoSizeHeight = true;
			this.bunifuTextBox7.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox7.BackgroundImage")));
			this.bunifuTextBox7.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox7.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuTextBox7.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox7.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox7.BorderRadius = 10;
			this.bunifuTextBox7.BorderThickness = 1;
			this.bunifuTextBox7.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.bunifuTextBox7.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox7.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox7.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.bunifuTextBox7.DefaultText = "";
			this.bunifuTextBox7.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuTextBox7.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuTextBox7.HideSelection = true;
			this.bunifuTextBox7.IconLeft = null;
			this.bunifuTextBox7.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox7.IconPadding = 10;
			this.bunifuTextBox7.IconRight = null;
			this.bunifuTextBox7.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox7.Lines = new string[0];
			this.bunifuTextBox7.Location = new System.Drawing.Point(60, 420);
			this.bunifuTextBox7.Margin = new System.Windows.Forms.Padding(6, 20, 6, 0);
			this.bunifuTextBox7.MaxLength = 32767;
			this.bunifuTextBox7.MinimumSize = new System.Drawing.Size(2, 2);
			this.bunifuTextBox7.Modified = false;
			this.bunifuTextBox7.Multiline = false;
			this.bunifuTextBox7.Name = "bunifuTextBox7";
			stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties9.FillColor = System.Drawing.Color.Empty;
			stateProperties9.ForeColor = System.Drawing.Color.Empty;
			stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox7.OnActiveState = stateProperties9;
			stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.bunifuTextBox7.OnDisabledState = stateProperties10;
			stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties11.FillColor = System.Drawing.Color.Empty;
			stateProperties11.ForeColor = System.Drawing.Color.Empty;
			stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox7.OnHoverState = stateProperties11;
			stateProperties12.BorderColor = System.Drawing.Color.Silver;
			stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			stateProperties12.ForeColor = System.Drawing.Color.Empty;
			stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox7.OnIdleState = stateProperties12;
			this.bunifuTextBox7.Padding = new System.Windows.Forms.Padding(6);
			this.bunifuTextBox7.PasswordChar = '\0';
			this.bunifuTextBox7.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox7.PlaceholderText = "ID를 입력해주세요.";
			this.bunifuTextBox7.ReadOnly = false;
			this.bunifuTextBox7.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox7.SelectedText = "";
			this.bunifuTextBox7.SelectionLength = 0;
			this.bunifuTextBox7.SelectionStart = 0;
			this.bunifuTextBox7.ShortcutsEnabled = true;
			this.bunifuTextBox7.Size = new System.Drawing.Size(411, 69);
			this.bunifuTextBox7.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox7.TabIndex = 20;
			this.bunifuTextBox7.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox7.TextMarginBottom = 0;
			this.bunifuTextBox7.TextMarginLeft = 3;
			this.bunifuTextBox7.TextMarginTop = 1;
			this.bunifuTextBox7.TextPlaceholder = "ID를 입력해주세요.";
			this.bunifuTextBox7.UseSystemPasswordChar = false;
			this.bunifuTextBox7.WordWrap = true;
			// 
			// panel9
			// 
			this.panel9.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel9.Location = new System.Drawing.Point(60, 390);
			this.panel9.Name = "panel9";
			this.panel9.Size = new System.Drawing.Size(411, 30);
			this.panel9.TabIndex = 19;
			// 
			// bunifuTextBox6
			// 
			this.bunifuTextBox6.AcceptsReturn = false;
			this.bunifuTextBox6.AcceptsTab = false;
			this.bunifuTextBox6.AnimationSpeed = 200;
			this.bunifuTextBox6.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox6.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox6.AutoSizeHeight = true;
			this.bunifuTextBox6.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox6.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox6.BackgroundImage")));
			this.bunifuTextBox6.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox6.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuTextBox6.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox6.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox6.BorderRadius = 10;
			this.bunifuTextBox6.BorderThickness = 1;
			this.bunifuTextBox6.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.bunifuTextBox6.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox6.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox6.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.bunifuTextBox6.DefaultText = "";
			this.bunifuTextBox6.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuTextBox6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuTextBox6.HideSelection = true;
			this.bunifuTextBox6.IconLeft = null;
			this.bunifuTextBox6.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox6.IconPadding = 10;
			this.bunifuTextBox6.IconRight = null;
			this.bunifuTextBox6.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox6.Lines = new string[0];
			this.bunifuTextBox6.Location = new System.Drawing.Point(60, 321);
			this.bunifuTextBox6.Margin = new System.Windows.Forms.Padding(6, 20, 6, 0);
			this.bunifuTextBox6.MaxLength = 32767;
			this.bunifuTextBox6.MinimumSize = new System.Drawing.Size(2, 2);
			this.bunifuTextBox6.Modified = false;
			this.bunifuTextBox6.Multiline = false;
			this.bunifuTextBox6.Name = "bunifuTextBox6";
			stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties13.FillColor = System.Drawing.Color.Empty;
			stateProperties13.ForeColor = System.Drawing.Color.Empty;
			stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox6.OnActiveState = stateProperties13;
			stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.bunifuTextBox6.OnDisabledState = stateProperties14;
			stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties15.FillColor = System.Drawing.Color.Empty;
			stateProperties15.ForeColor = System.Drawing.Color.Empty;
			stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox6.OnHoverState = stateProperties15;
			stateProperties16.BorderColor = System.Drawing.Color.Silver;
			stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			stateProperties16.ForeColor = System.Drawing.Color.Empty;
			stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox6.OnIdleState = stateProperties16;
			this.bunifuTextBox6.Padding = new System.Windows.Forms.Padding(6);
			this.bunifuTextBox6.PasswordChar = '\0';
			this.bunifuTextBox6.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox6.PlaceholderText = "ID를 입력해주세요.";
			this.bunifuTextBox6.ReadOnly = false;
			this.bunifuTextBox6.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox6.SelectedText = "";
			this.bunifuTextBox6.SelectionLength = 0;
			this.bunifuTextBox6.SelectionStart = 0;
			this.bunifuTextBox6.ShortcutsEnabled = true;
			this.bunifuTextBox6.Size = new System.Drawing.Size(411, 69);
			this.bunifuTextBox6.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox6.TabIndex = 18;
			this.bunifuTextBox6.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox6.TextMarginBottom = 0;
			this.bunifuTextBox6.TextMarginLeft = 3;
			this.bunifuTextBox6.TextMarginTop = 1;
			this.bunifuTextBox6.TextPlaceholder = "ID를 입력해주세요.";
			this.bunifuTextBox6.UseSystemPasswordChar = false;
			this.bunifuTextBox6.WordWrap = true;
			// 
			// panel8
			// 
			this.panel8.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel8.Location = new System.Drawing.Point(60, 291);
			this.panel8.Name = "panel8";
			this.panel8.Size = new System.Drawing.Size(411, 30);
			this.panel8.TabIndex = 17;
			// 
			// bunifuTextBox5
			// 
			this.bunifuTextBox5.AcceptsReturn = false;
			this.bunifuTextBox5.AcceptsTab = false;
			this.bunifuTextBox5.AnimationSpeed = 200;
			this.bunifuTextBox5.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox5.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox5.AutoSizeHeight = true;
			this.bunifuTextBox5.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox5.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox5.BackgroundImage")));
			this.bunifuTextBox5.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox5.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuTextBox5.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox5.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox5.BorderRadius = 10;
			this.bunifuTextBox5.BorderThickness = 1;
			this.bunifuTextBox5.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.bunifuTextBox5.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox5.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox5.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.bunifuTextBox5.DefaultText = "";
			this.bunifuTextBox5.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuTextBox5.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuTextBox5.HideSelection = true;
			this.bunifuTextBox5.IconLeft = null;
			this.bunifuTextBox5.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox5.IconPadding = 10;
			this.bunifuTextBox5.IconRight = null;
			this.bunifuTextBox5.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox5.Lines = new string[0];
			this.bunifuTextBox5.Location = new System.Drawing.Point(60, 225);
			this.bunifuTextBox5.Margin = new System.Windows.Forms.Padding(6, 20, 6, 20);
			this.bunifuTextBox5.MaxLength = 32767;
			this.bunifuTextBox5.MinimumSize = new System.Drawing.Size(2, 2);
			this.bunifuTextBox5.Modified = false;
			this.bunifuTextBox5.Multiline = false;
			this.bunifuTextBox5.Name = "bunifuTextBox5";
			stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties17.FillColor = System.Drawing.Color.Empty;
			stateProperties17.ForeColor = System.Drawing.Color.Empty;
			stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox5.OnActiveState = stateProperties17;
			stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.bunifuTextBox5.OnDisabledState = stateProperties18;
			stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties19.FillColor = System.Drawing.Color.Empty;
			stateProperties19.ForeColor = System.Drawing.Color.Empty;
			stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox5.OnHoverState = stateProperties19;
			stateProperties20.BorderColor = System.Drawing.Color.Silver;
			stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			stateProperties20.ForeColor = System.Drawing.Color.Empty;
			stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox5.OnIdleState = stateProperties20;
			this.bunifuTextBox5.Padding = new System.Windows.Forms.Padding(6);
			this.bunifuTextBox5.PasswordChar = '*';
			this.bunifuTextBox5.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox5.PlaceholderText = "비밀번호를 입력해주세요.";
			this.bunifuTextBox5.ReadOnly = false;
			this.bunifuTextBox5.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox5.SelectedText = "";
			this.bunifuTextBox5.SelectionLength = 0;
			this.bunifuTextBox5.SelectionStart = 0;
			this.bunifuTextBox5.ShortcutsEnabled = true;
			this.bunifuTextBox5.Size = new System.Drawing.Size(411, 66);
			this.bunifuTextBox5.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox5.TabIndex = 16;
			this.bunifuTextBox5.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox5.TextMarginBottom = 0;
			this.bunifuTextBox5.TextMarginLeft = 3;
			this.bunifuTextBox5.TextMarginTop = 1;
			this.bunifuTextBox5.TextPlaceholder = "비밀번호를 입력해주세요.";
			this.bunifuTextBox5.UseSystemPasswordChar = false;
			this.bunifuTextBox5.WordWrap = true;
			// 
			// panel6
			// 
			this.panel6.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel6.Location = new System.Drawing.Point(60, 195);
			this.panel6.Name = "panel6";
			this.panel6.Size = new System.Drawing.Size(411, 30);
			this.panel6.TabIndex = 15;
			// 
			// bunifuTextBox4
			// 
			this.bunifuTextBox4.AcceptsReturn = false;
			this.bunifuTextBox4.AcceptsTab = false;
			this.bunifuTextBox4.AnimationSpeed = 200;
			this.bunifuTextBox4.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox4.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox4.AutoSizeHeight = true;
			this.bunifuTextBox4.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox4.BackgroundImage")));
			this.bunifuTextBox4.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox4.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuTextBox4.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox4.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox4.BorderRadius = 10;
			this.bunifuTextBox4.BorderThickness = 1;
			this.bunifuTextBox4.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.bunifuTextBox4.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox4.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox4.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.bunifuTextBox4.DefaultText = "";
			this.bunifuTextBox4.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuTextBox4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuTextBox4.HideSelection = true;
			this.bunifuTextBox4.IconLeft = null;
			this.bunifuTextBox4.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox4.IconPadding = 10;
			this.bunifuTextBox4.IconRight = null;
			this.bunifuTextBox4.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox4.Lines = new string[0];
			this.bunifuTextBox4.Location = new System.Drawing.Point(60, 129);
			this.bunifuTextBox4.Margin = new System.Windows.Forms.Padding(6, 20, 6, 20);
			this.bunifuTextBox4.MaxLength = 32767;
			this.bunifuTextBox4.MinimumSize = new System.Drawing.Size(2, 2);
			this.bunifuTextBox4.Modified = false;
			this.bunifuTextBox4.Multiline = false;
			this.bunifuTextBox4.Name = "bunifuTextBox4";
			stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties21.FillColor = System.Drawing.Color.Empty;
			stateProperties21.ForeColor = System.Drawing.Color.Empty;
			stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox4.OnActiveState = stateProperties21;
			stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.bunifuTextBox4.OnDisabledState = stateProperties22;
			stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties23.FillColor = System.Drawing.Color.Empty;
			stateProperties23.ForeColor = System.Drawing.Color.Empty;
			stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox4.OnHoverState = stateProperties23;
			stateProperties24.BorderColor = System.Drawing.Color.Silver;
			stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			stateProperties24.ForeColor = System.Drawing.Color.Empty;
			stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox4.OnIdleState = stateProperties24;
			this.bunifuTextBox4.Padding = new System.Windows.Forms.Padding(6);
			this.bunifuTextBox4.PasswordChar = '*';
			this.bunifuTextBox4.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox4.PlaceholderText = "비밀번호를 입력해주세요.";
			this.bunifuTextBox4.ReadOnly = false;
			this.bunifuTextBox4.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox4.SelectedText = "";
			this.bunifuTextBox4.SelectionLength = 0;
			this.bunifuTextBox4.SelectionStart = 0;
			this.bunifuTextBox4.ShortcutsEnabled = true;
			this.bunifuTextBox4.Size = new System.Drawing.Size(411, 66);
			this.bunifuTextBox4.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox4.TabIndex = 14;
			this.bunifuTextBox4.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox4.TextMarginBottom = 0;
			this.bunifuTextBox4.TextMarginLeft = 3;
			this.bunifuTextBox4.TextMarginTop = 1;
			this.bunifuTextBox4.TextPlaceholder = "비밀번호를 입력해주세요.";
			this.bunifuTextBox4.UseSystemPasswordChar = false;
			this.bunifuTextBox4.WordWrap = true;
			// 
			// panel5
			// 
			this.panel5.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel5.Location = new System.Drawing.Point(60, 99);
			this.panel5.Name = "panel5";
			this.panel5.Size = new System.Drawing.Size(411, 30);
			this.panel5.TabIndex = 13;
			// 
			// bunifuTextBox3
			// 
			this.bunifuTextBox3.AcceptsReturn = false;
			this.bunifuTextBox3.AcceptsTab = false;
			this.bunifuTextBox3.AnimationSpeed = 200;
			this.bunifuTextBox3.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
			this.bunifuTextBox3.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
			this.bunifuTextBox3.AutoSizeHeight = true;
			this.bunifuTextBox3.BackColor = System.Drawing.Color.Transparent;
			this.bunifuTextBox3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox3.BackgroundImage")));
			this.bunifuTextBox3.BorderColorActive = System.Drawing.Color.DodgerBlue;
			this.bunifuTextBox3.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			this.bunifuTextBox3.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			this.bunifuTextBox3.BorderColorIdle = System.Drawing.Color.Silver;
			this.bunifuTextBox3.BorderRadius = 10;
			this.bunifuTextBox3.BorderThickness = 1;
			this.bunifuTextBox3.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
			this.bunifuTextBox3.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
			this.bunifuTextBox3.Cursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox3.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
			this.bunifuTextBox3.DefaultText = "";
			this.bunifuTextBox3.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuTextBox3.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			this.bunifuTextBox3.HideSelection = true;
			this.bunifuTextBox3.IconLeft = null;
			this.bunifuTextBox3.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox3.IconPadding = 10;
			this.bunifuTextBox3.IconRight = null;
			this.bunifuTextBox3.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
			this.bunifuTextBox3.Lines = new string[0];
			this.bunifuTextBox3.Location = new System.Drawing.Point(60, 30);
			this.bunifuTextBox3.Margin = new System.Windows.Forms.Padding(6, 20, 6, 0);
			this.bunifuTextBox3.MaxLength = 32767;
			this.bunifuTextBox3.MinimumSize = new System.Drawing.Size(2, 2);
			this.bunifuTextBox3.Modified = false;
			this.bunifuTextBox3.Multiline = false;
			this.bunifuTextBox3.Name = "bunifuTextBox3";
			stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
			stateProperties25.FillColor = System.Drawing.Color.Empty;
			stateProperties25.ForeColor = System.Drawing.Color.Empty;
			stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox3.OnActiveState = stateProperties25;
			stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
			stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
			stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
			stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
			this.bunifuTextBox3.OnDisabledState = stateProperties26;
			stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
			stateProperties27.FillColor = System.Drawing.Color.Empty;
			stateProperties27.ForeColor = System.Drawing.Color.Empty;
			stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox3.OnHoverState = stateProperties27;
			stateProperties28.BorderColor = System.Drawing.Color.Silver;
			stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(239)))), ((int)(((byte)(239)))), ((int)(((byte)(239)))));
			stateProperties28.ForeColor = System.Drawing.Color.Empty;
			stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
			this.bunifuTextBox3.OnIdleState = stateProperties28;
			this.bunifuTextBox3.Padding = new System.Windows.Forms.Padding(6);
			this.bunifuTextBox3.PasswordChar = '\0';
			this.bunifuTextBox3.PlaceholderForeColor = System.Drawing.Color.Silver;
			this.bunifuTextBox3.PlaceholderText = "ID를 입력해주세요.";
			this.bunifuTextBox3.ReadOnly = false;
			this.bunifuTextBox3.ScrollBars = System.Windows.Forms.ScrollBars.None;
			this.bunifuTextBox3.SelectedText = "";
			this.bunifuTextBox3.SelectionLength = 0;
			this.bunifuTextBox3.SelectionStart = 0;
			this.bunifuTextBox3.ShortcutsEnabled = true;
			this.bunifuTextBox3.Size = new System.Drawing.Size(411, 69);
			this.bunifuTextBox3.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
			this.bunifuTextBox3.TabIndex = 12;
			this.bunifuTextBox3.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
			this.bunifuTextBox3.TextMarginBottom = 0;
			this.bunifuTextBox3.TextMarginLeft = 3;
			this.bunifuTextBox3.TextMarginTop = 1;
			this.bunifuTextBox3.TextPlaceholder = "ID를 입력해주세요.";
			this.bunifuTextBox3.UseSystemPasswordChar = false;
			this.bunifuTextBox3.WordWrap = true;
			// 
			// panel4
			// 
			this.panel4.Dock = System.Windows.Forms.DockStyle.Top;
			this.panel4.Location = new System.Drawing.Point(60, 0);
			this.panel4.Name = "panel4";
			this.panel4.Size = new System.Drawing.Size(411, 30);
			this.panel4.TabIndex = 11;
			// 
			// pictureBox2
			// 
			this.pictureBox2.BackColor = System.Drawing.Color.Transparent;
			this.pictureBox2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
			this.pictureBox2.Dock = System.Windows.Forms.DockStyle.Top;
			this.pictureBox2.Image = global::WindowsFormsApp1.Properties.Resources.BCU_Logo;
			this.pictureBox2.Location = new System.Drawing.Point(0, 0);
			this.pictureBox2.Margin = new System.Windows.Forms.Padding(6);
			this.pictureBox2.Name = "pictureBox2";
			this.pictureBox2.Size = new System.Drawing.Size(531, 220);
			this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.pictureBox2.TabIndex = 6;
			this.pictureBox2.TabStop = false;
			// 
			// bunifuPanel1
			// 
			this.bunifuPanel1.BackgroundColor = System.Drawing.Color.Transparent;
			this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
			this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
			this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
			this.bunifuPanel1.BorderRadius = 3;
			this.bunifuPanel1.BorderThickness = 1;
			this.bunifuPanel1.Controls.Add(this.bunifuFormCaptionButton2);
			this.bunifuPanel1.Controls.Add(this.bunifuFormCaptionButton1);
			this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Top;
			this.bunifuPanel1.Location = new System.Drawing.Point(547, 0);
			this.bunifuPanel1.Name = "bunifuPanel1";
			this.bunifuPanel1.ShowBorders = true;
			this.bunifuPanel1.Size = new System.Drawing.Size(887, 62);
			this.bunifuPanel1.TabIndex = 3;
			// 
			// bunifuFormDock_panel1
			// 
			this.bunifuFormDock_panel1.AllowFormDragging = true;
			this.bunifuFormDock_panel1.AllowFormDropShadow = true;
			this.bunifuFormDock_panel1.AllowFormResizing = false;
			this.bunifuFormDock_panel1.AllowHidingBottomRegion = true;
			this.bunifuFormDock_panel1.AllowOpacityChangesWhileDragging = false;
			this.bunifuFormDock_panel1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_panel1.BorderOptions.BottomBorder.BorderThickness = 1;
			this.bunifuFormDock_panel1.BorderOptions.BottomBorder.ShowBorder = true;
			this.bunifuFormDock_panel1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_panel1.BorderOptions.LeftBorder.BorderThickness = 1;
			this.bunifuFormDock_panel1.BorderOptions.LeftBorder.ShowBorder = true;
			this.bunifuFormDock_panel1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_panel1.BorderOptions.RightBorder.BorderThickness = 1;
			this.bunifuFormDock_panel1.BorderOptions.RightBorder.ShowBorder = true;
			this.bunifuFormDock_panel1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
			this.bunifuFormDock_panel1.BorderOptions.TopBorder.BorderThickness = 1;
			this.bunifuFormDock_panel1.BorderOptions.TopBorder.ShowBorder = true;
			this.bunifuFormDock_panel1.ContainerControl = this;
			this.bunifuFormDock_panel1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
			this.bunifuFormDock_panel1.DockingIndicatorsOpacity = 0.5D;
			this.bunifuFormDock_panel1.DockingOptions.DockAll = true;
			this.bunifuFormDock_panel1.DockingOptions.DockBottomLeft = true;
			this.bunifuFormDock_panel1.DockingOptions.DockBottomRight = true;
			this.bunifuFormDock_panel1.DockingOptions.DockFullScreen = true;
			this.bunifuFormDock_panel1.DockingOptions.DockLeft = true;
			this.bunifuFormDock_panel1.DockingOptions.DockRight = true;
			this.bunifuFormDock_panel1.DockingOptions.DockTopLeft = true;
			this.bunifuFormDock_panel1.DockingOptions.DockTopRight = true;
			this.bunifuFormDock_panel1.FormDraggingOpacity = 0.9D;
			this.bunifuFormDock_panel1.ParentForm = this;
			this.bunifuFormDock_panel1.ShowCursorChanges = true;
			this.bunifuFormDock_panel1.ShowDockingIndicators = false;
			this.bunifuFormDock_panel1.TitleBarOptions.AllowFormDragging = true;
			this.bunifuFormDock_panel1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock_panel1;
			this.bunifuFormDock_panel1.TitleBarOptions.DoubleClickToExpandWindow = true;
			this.bunifuFormDock_panel1.TitleBarOptions.TitleBarControl = this.bunifuPanel1;
			this.bunifuFormDock_panel1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
			// 
			// Form1
			// 
			this.AutoScaleDimensions = new System.Drawing.SizeF(13F, 24F);
			this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
			this.BackgroundImage = global::WindowsFormsApp1.Properties.Resources.학교background;
			this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
			this.ClientSize = new System.Drawing.Size(1434, 948);
			this.Controls.Add(this.bunifuPanel1);
			this.Controls.Add(this.bunifuPages1);
			this.Cursor = System.Windows.Forms.Cursors.Default;
			this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
			this.Margin = new System.Windows.Forms.Padding(6);
			this.Name = "Form1";
			this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "Form1";
			((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
			this.tabPage1.ResumeLayout(false);
			this.bunifuPanel2.ResumeLayout(false);
			this.panel3.ResumeLayout(false);
			this.panel3.PerformLayout();
			this.bunifuPages1.ResumeLayout(false);
			this.tabPage2.ResumeLayout(false);
			this.bunifuPanel3.ResumeLayout(false);
			this.panel11.ResumeLayout(false);
			((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
			this.bunifuPanel1.ResumeLayout(false);
			this.ResumeLayout(false);

		}

		#endregion
		private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock_form;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
		private System.Windows.Forms.PictureBox pictureBox1;
		private Bunifu.UI.WinForms.BunifuFormCaptionButton bunifuFormCaptionButton1;
		private Bunifu.UI.WinForms.BunifuFormCaptionButton bunifuFormCaptionButton2;
		private System.Windows.Forms.LinkLabel linkLabel2;
		private System.Windows.Forms.LinkLabel linkLabel1;
		private Bunifu.UI.WinForms.BunifuPages bunifuPages1;
		private System.Windows.Forms.TabPage tabPage1;
		private System.Windows.Forms.TabPage tabPage2;
		private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
		private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox2;
		private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
		private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock_panel1;
		private System.Windows.Forms.PictureBox pictureBox2;
		private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
		private System.Windows.Forms.Panel panel3;
		private System.Windows.Forms.Panel panel1;
		private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
		private System.Windows.Forms.Panel panel2;
		private System.Windows.Forms.Panel panel7;
		private System.Windows.Forms.Panel panel11;
		private System.Windows.Forms.Panel panel10;
		private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox7;
		private System.Windows.Forms.Panel panel9;
		private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox6;
		private System.Windows.Forms.Panel panel8;
		private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox5;
		private System.Windows.Forms.Panel panel6;
		private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox4;
		private System.Windows.Forms.Panel panel5;
		private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox3;
		private System.Windows.Forms.Panel panel4;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton22;
		private System.Windows.Forms.Panel panel12;
		private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton23;
	}
}

